### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by dmullerd** [adamdehaven/Specify#1]
Hi, Is there a way to specify units?
I'm drawing in mm. To test the script, I created a circle that is 50mm in diameter. Then I ran the script and it created a dimension line that says "12." See below.

Thanks,
D.

![screen shot 2015-05-07 at 2 14 52 pm](https://cloud.githubusercontent.com/assets/6380551/7509460/80529ecc-f4c3-11e4-898f-7cddcf6e9b7c.png)

**Comment by adamdehaven** [comment]
@dmullerd I have a switch statement in the script that detects the document's ruler units (in your case, millimeters) but I can't figure out what I did for the conversion as I wrote this script a while back. It's based on the Document's units when you initially create it, or by showing the Ruler in Illustrator and then changing the units before running the script. The `switch` statement does run correctly, but I can't figure out what the conversion should be.

The relevant code is below; maybe you or someone else can figure out what I'm missing?

```
switch (doc.rulerUnits) {
	case RulerUnits.Inches:
		v = val/dpi;
		v = v.toFixed (decimals);
		break;

	case RulerUnits.Centimeters:
		v = val/(dpi/2.54);
		v = v.toFixed (decimals);
		break;

	case RulerUnits.Millimeters:
		v = val/(dpi/25.4);
		v = v.toFixed (decimals);
		break;

	case RulerUnits.Picas:
		v = val/(dpi/6);
		var vd = v - Math.floor (v);
		vd = 12*vd;
		v =  Math.floor(v)+'p'+vd.toFixed (decimals);
		break;

	default:
		v = v.toFixed (decimals);
}
```

**Comment by adamdehaven** [comment]
@dmullerd - I have updated the script to allow for specifying units, along with outputting a unit label. The units label is optional with a checkbox included in the popup to turn on or off.

> 1. [Download](https://github.com/adamdehaven/Specify/archive/master.zip) and install the new script.
> 2. In your document, show Rulers `View > Rulers > Show Rulers` ( <kbd>⌘Cmd</kbd> + <kbd>R</kbd> on Mac, <kbd>Ctrl</kbd> + <kbd>R</kbd> on PC )
> 3. Right click on the Ruler, and select your desired units. The script will by default use the Document's selected units.
> 4. Run the script and you will now get output as shown in the example below
>    ![specify-with-mm](https://cloud.githubusercontent.com/assets/2229946/7686566/a86d349a-fd64-11e4-8082-badb5fb2f086.jpg)

Let me know how this works for you!
