### ISSUE TITLE
when specifying measurements of a dashed line, the specify line is dashed as well

### ISSUE THREAD

**Issue by KevinConsen** [adamdehaven/Specify#11]
I just noticed when trying to specify a dash-lined element that the line to specify the length was also dashed. I found it rather funny, but I can also imagine that this is not supposed to happen :P

![Dashed line](http://i.imgur.com/Tm6oNA9.png)

**Comment by adamdehaven** [comment]
I can confirm the behavior, and obviously it's not intended. I'm looking into it. Thanks!

**Comment by adamdehaven** [comment]
@KevinConsen Fixed... please download version 1.2.2 and let me know if this fixed the issue for you as well. Thanks again!

**Comment by yuusuf-sallahuddin** [comment]
Confirmed fixed :) Thanks again.
