### ISSUE TITLE
Detect Document Color Mode

### ISSUE THREAD

**Issue by adamdehaven** [adamdehaven/Specify#13]
Add a switch in the script to detect document color mode (RGB vs. CYMK) to allow user to specify the color of the dimension lines and text.

**Comment by schroef** [comment]
Doesnt matter if it knows what the document mode is. Color mode doesn't matter or isnt really important because it will be transformed automatically. It was the first thing I was thinking about when using it just now.

**Comment by schroef** [comment]
I was testing the native java color picker script which opens OS color picker. Somehow in OSX it close also the dialog window. Then i tried a couple of other versions and found a super nice one. One small thing is that your setup uses string input for the color code and lots of code is setup for that. So i simply converted the result of the color picker to a string and slice it in 3.

Looks much better doesn't :) I think its easier that using those split RGB value, this is a bit more complicated with the second script. Current it lives aside your script and i include it.
![added-colorpicker](https://user-images.githubusercontent.com/6923008/81628082-b99eeb00-93cd-11ea-8b08-c127656e2dbb.gif)

Know i only need to work on starting the defaults properly

**Comment by adamdehaven** [comment]
This looks really nice. I should have some time to take a closer look this weekend

**Comment by schroef** [comment]
I can setup a repo and make a pull request if you're okay with that. Saves time and also why do work which is already done?

PS I also added the head & tail size and also stroke width. I found them a bit tiny and I saw you have hardcoded them.

One issue I found, not sure where things go wrong, is that restore defaults doesn't seem to reset all fields. Items like decimal and custom unit are not restored, but their setup seems properly done. The function restore.... should work just fine.
![Screen Shot 2020-05-12 at 11 28 09](https://user-images.githubusercontent.com/6923008/81713595-13da9300-9444-11ea-98a3-5457cb63f970.png)
![Screen Shot 2020-05-12 at 11 28 02](https://user-images.githubusercontent.com/6923008/81713601-150bc000-9444-11ea-9b39-dac4e5e63553.png)

**Comment by schroef** [comment]
PS is it perhaps an idea to put items in a tabbed dialog window. Its already quite big and I got a feeling it overwhelmed a user. Perhaps you know this AWESOME perhaps not. But on https://scriptui.joonas.me/ you can build dialog panels using a online build components, its made by Joonas and so nice to build a panel like this. Way and way better, easier and direct visual feedback how it will look. You can download the script and you can also upload it again if you need to change something. It does add extra code for the online editor, but you can strip that out when you about to use this code.

Anyways, I was think perhaps it is better if some settings of this panel are put into tabs. That way it sort looks less overwhelming. Is that a good idea perhaps? It looks much nicer, shows much nicer on screen

![Screen Shot 2020-05-12 at 12 19 35](https://user-images.githubusercontent.com/6923008/81719305-e513eb00-944a-11ea-9013-cc122a8e7798.png)
![Screen Shot 2020-05-12 at 12 09 37](https://user-images.githubusercontent.com/6923008/81719308-e6451800-944a-11ea-8a6b-1ee728a5519a.png)

**Comment by adamdehaven** [comment]
@schroef if you'd like to submit a pull request for the initial color picker addition (without the new tabbed interface), I'll definitely take a look. I appreciate the work you put into it!

For the tabbed interface, if you'd like, you can submit a separate pull request for that as well.

**Comment by adamdehaven** [comment]
@schroef I had some time this evening and I implemented a new UI based on the tabbed interface you suggested (not merged into master yet). If you're going to open a pull request, just include the color picker, and the head, tail size, and stroke width. 🎉

**Comment by schroef** [comment]
Nice man! Yeah i was looking at the branches and noticed some code from the scriptui site. So i though ow he already knows. Then i i tried fixing the current UI thinking that backup JSON was that UI. hahahah tada that was the new UI you was working, was a nice surprise to see that.

I made a new post for the color picker dialog #17 I did some more tweaker making it all a bit more organised and cleaner look. But perhaps that's not important if its gonna change. PS a horizontal tabbed menu is also nice. I was thinking perhaps the vertical one wastes a lot of space on the left. WIth that website you can change it super easy, that's why i like it so much. Only thing is once you start adding functionality you need to take note of what goes where.

**Comment by adamdehaven** [comment]
Resolved with v2.0.0
