### ISSUE TITLE
Ability to adjust size of leader lines

### ISSUE THREAD

**Issue by chancrescolex** [adamdehaven/Specify#14]
I'm not sure if leader line is the correct term, but I'm referring to the 2 lines perpendicular to the edge being defined, The size of these lines looks fine in your examples where the edge is 200px - 1000px, but the larger the size of the artwork, the more these lines get lost and the parallel line becomes too close to the edge being defined.

I'm not sure of the best implementation, but maybe it could be automatically sized based on the size of the art or possibly something like 50% of the dimension font size.

Please see attached images for further clarification.

![Normal leaders on 48" box](https://user-images.githubusercontent.com/1666489/55174919-b490c500-5154-11e9-9aec-66b36f1be5d2.JPG)

![Possible modification](https://user-images.githubusercontent.com/1666489/55174918-b3f82e80-5154-11e9-9e17-6cf997060373.JPG)

**Comment by adamdehaven** [comment]
I think this is a great feature request and I've been looking into whether I can reasonably make the lines dynamic depending on the artwork, however, there's a lot of variables to consider for all users (artboard size, scale, etc.). 

I don't currently see a clear path towards a universal solution, so in the meantime, I have a bit of a workaround you can implement by editing the `Specify.jsx` file:


To increase the stroke width of the lines, edit line **784** 

```
path.strokeWidth = 0.5; // Increase the value for a thicker line
```

To increase the gap between the object and the lines, pass both values through the `convertToPoints` function for lines **390** and **393**:

```
var gap = convertToPoints(4);

var size = convertToPoints(6);
```

Hopefully this helps. I'm going to close the issue for the time-being, however, anyone ending up on this thread down the line that would like to contribute is more than welcome to [open a pull request](https://github.com/adamdehaven/specify/pulls) with a viable solution to dynamically adjust the stroke width and dimension lines.

@chancrescolex if you need any further help, let me know!

**Comment by adamdehaven** [comment]
@chancrescolex Late reply, but I believe your request has now been resolved and is integrated into the latest version of the extension 🎉
