### ISSUE TITLE
Layout Adjustment

### ISSUE THREAD

**Issue by alexleitte** [adamdehaven/Specify#15]
First, this script is fantastic... I just start to use it and im impressioned with his possibilities.
It will help me a lot.

I have an idea to turn his layout into something more intuitive. 
What about changing the buttons into an axis? I made a study... I hope you appreciate it.

![image](https://user-images.githubusercontent.com/54675664/63961780-eb526a80-ca67-11e9-8faa-208fd7652bf1.png)

**Comment by adamdehaven** [comment]
Unfortunately layouts like your example aren't totally compatible with all versions of Adobe Illustrator that I try to support.

**Comment by alexleitte** [comment]
What about trying a sequence more friendly, like:

LEFT / TOP / BOTTOM / RIGHT

It's just because in actually way, we have RIGHT at the left side and LEFT at the right side...
