### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by crzyss** [adamdehaven/Specify#16]
its will be completed tool if we have select custome font. Becouse I using Adobe Midle East Version. Onece i run this script text comming Arabic Numbers
![Screen Shot 2020-03-11 at 4 48 59 PM](https://user-images.githubusercontent.com/20498727/76423782-5803d580-63b8-11ea-90d3-b858cdab8564.png)

**Comment by crzyss** [comment]
I solved this issed after few minutes and i sound solution on illustrator. I change default character styles. if some one have special midle east follow
![Screen Shot 2020-03-11 at 4 57 10 PM](https://user-images.githubusercontent.com/20498727/76424571-75856f00-63b9-11ea-8fb9-35c9d0fc9c10.png)
![Screen Shot 2020-03-11 at 4 57 01 PM](https://user-images.githubusercontent.com/20498727/76424573-774f3280-63b9-11ea-974b-c0fa86aa1a2a.png)
![Screen Shot 2020-03-11 at 4 57 16 PM](https://user-images.githubusercontent.com/20498727/76424577-77e7c900-63b9-11ea-87b0-ff3a0fe13485.png)

**Comment by adamdehaven** [comment]
@crzyss I'm glad you were able to figure it out. Nice job!
