### ISSUE TITLE
Color Picker Dialog branch

### ISSUE THREAD

**Issue by schroef** [adamdehaven/Specify#17]
Hi Adam,

i just did some work on the color picker dialog. I noticed you already started making a new UI, that's super nice. That https://scriptui.joonas.me/ site is pretty handy right. Only thing you need to build in is the functionality. But i find this so much faster and its also great for seeing issues immediately without having to launch an Adobe app and run the script.

I did some minor clean up now. I noticed the panels weren't aligning really nice, so i set them all to fill. I also tweaked the margins a bit here and there, looks a bit cleaner now. I put the custom unit aside of the checkbox options since it basically showed the same title twice, this saves space. I also made it less wide or was it that wide on purpose? I also simplified the labels, they were a bit to subscription perhaps and all that info is also in the tooltip already. So shorter labels look cleaner again :)

I did take out that into at the top, I'm not sure why its there. Its not clickable or anything and people can find the URL in the script. I would leave out or when the other UI Dialog gets there over time, perhaps that one can have it. 

Do you mind if i also add gap size into this branch. I just added it and works properly. Im not 100% if the layout should be like this though. I was thinking of putting the stroke setting perhaps on the same line so it looks less messy on that line. But thing is, they all belong together since all are for the measurement lines.

![specify-dialog-comparing](https://user-images.githubusercontent.com/6923008/81770637-e24ae180-94ae-11ea-9277-3efadba97df1.png)
_comparing current vs color picker dialog_

**Comment by schroef** [comment]
PS that persistent mode you build in, is that the official way for Illustrator to do it like that? I also do some photoshop scripting and have been busy with updating an extension panel. The way persistence works in photoshop is really different. But perhaps that's the difference with using js and jsx script it guess. I don't know that much about it. I sort of understand it, but I'm no developer in any means, I'm a graphic designer actually.

**Comment by schroef** [comment]
I see i need to change the gap behavior, i did noticed it earlier this still uses internal pixels methods. I see you have added the conversion function, so using that should not be an issue i think. 

EDIT
Well that seems for pt to custom value. hmmm hope i can figure out how to do this one

**Comment by schroef** [comment]
Ive updated both gap and size, they will now use doc ruler settings. Thats seem more useful than the internal px value right?

**Comment by adamdehaven** [comment]
@schroef Ok, do you want to push the code so I can take a look?

As for the persistent settings, I believe this is specific to .jsx

**Comment by schroef** [comment]
I guess that would be it, i need to read more about that those methods and how to use that.

PS why didn't or don't you make an extension panel of this script? That would be much more convenient, styling can be done complete custom. It could be localized.

I was looking at [Creative Cloud](https://exchange.adobe.com/creativecloud.html?q=dimension) and those things are price. One I saw is $74,- !!!! the other $19,99 I bet there are more. Though I know these things are quite time-consuming to prepare and code because of so much extra bottlenecks and such. It does give much more freedom and most important panel stays open

**Comment by schroef** [comment]
Ps i got the branch here, i wasn't sure if I should do a pull straight away. Im still doing cleaning of my left overs
https://github.com/schroef/Specify/tree/color-picker-dialog

**Comment by schroef** [comment]
I did some more work on a separated branch. Ive split the label and lines part a bit better. Now lines items are at the bottom and all inputs also have measurement indication. Though perhaps its cleaner to add a title label for that, i find all those indicators a bit distracting.

Ive also added the option to color lines separate from the label color. I guess that can be handy as well

![specify-dialog](https://user-images.githubusercontent.com/6923008/81890572-42f02200-9574-11ea-8c6c-0d3269000f82.png)

**Comment by adamdehaven** [comment]
@schroef I've got a working version put together on 2 separate branches. Here are screenshots of the new UI - what are your thoughts? I've changed to a tabbed interface like you suggested. I like the idea of separating the different settings on separate tabs.

![options](https://user-images.githubusercontent.com/2229946/81934960-d6017a00-95bd-11ea-8fbb-af80466187b5.png)
![styles](https://user-images.githubusercontent.com/2229946/81934965-d8fc6a80-95bd-11ea-9f3c-2254f7368935.png)
![defaults](https://user-images.githubusercontent.com/2229946/81934967-da2d9780-95bd-11ea-869a-394fa870b2fc.png)

**Comment by schroef** [comment]
Looks really nice indeed. My only thought is that the labels shouldn't be that long, it looks a bit messy I think. In my branches I tried shortening them since they also have a tooltip. For instance the color picker. I initially had click on it, but every user knows how this works. So I removed it, looks cleaner to me.

I think it will also look nice if that update button is in a tab

**Comment by schroef** [comment]
What you think of a horizontal tabbed menu style. This one also looks very pleasing. If I compare it to the vertical version, I see less waste of space. The vertical one has a bit of waste space due to the width of the panel for the menu.

![specify-dialog-horizontal-tabs](https://user-images.githubusercontent.com/6923008/81985817-c22d3680-9604-11ea-923d-5f934a50c64e.png)

**Comment by adamdehaven** [comment]
I made a ton of progress tonight (including some of your suggestions), but I forgot to upload the screenshots before I turned off my computer, so I'll update tomorrow. 

One thing I'm struggling with is including the colorPicker.js script. I have the include working; however, I don't want users to have to manage 2 separate files. 

It says in the docs that you can include the script within your file (literally copy and paste at the top of the file), but that seems less-than-ideal since it pushes my code down thousands of lines. 

I don't think there are any other options though, are there?

**Comment by adamdehaven** [comment]
@schroef Here's where I'm at so far. I really think this is the layout to go with. Just trying to do more research on including the colorPicker.js script, like I talked about above ^ .

![options](https://user-images.githubusercontent.com/2229946/82102686-48697b80-96de-11ea-995e-d026c196fd68.png)
![styles](https://user-images.githubusercontent.com/2229946/82102689-4a333f00-96de-11ea-8dd3-ffc9adef8784.png)
![updates](https://user-images.githubusercontent.com/2229946/82102690-4bfd0280-96de-11ea-81c4-43e4417d6fb1.png)

**Comment by schroef** [comment]
Looking good! Question, does the tabbed menu work for you? For me it crash illustrator 2017 and 2018 when I cancel the window. I was busy last night and spend hours figuring this out. It seems it is a known bug for InDesign 2017 and they released a fix. I tried using some parts of that and installed them inside illustrator app but it doesn't work.

Then I found a different script which sort of does what your script does, though with less settings. Nice thing is that it's a palette, so it stays open until you manually close it. In the palette window horizontal menu does work. I was testing it but I can't get the functions to run properly. I saw in the other script the guy added event listeners, I guess the palette works different compared to the dialog. In the palette the for lop to check the selection index doesn't do anything. With the dialog it simply works. I really like the horizontal version because it takes up less space. I also like the palette because it allows you to keep it open and do multiple runs in your document without needing to find the script and execute each time. Downside is, that the setup is way more complicated. I can post a link to that script if your interested. It's a super tiny window but has lots of power. I also noticed when I converted the current one to a palette that it is really slow as well. I guess adding all functions inside one function isn't a good setup for that one.

**Comment by schroef** [comment]
I do wonder if the input fields need to be that wide, they look huge now? Still think the color button doesn't need any text, it doesn't even need a label I think.

**Comment by adamdehaven** [comment]
@schroef Try downloading the `new-dialog-ui` branch and running in Illustrator 17/18 and see if it crashes for you? The inputs are wider because often times if I'm working in inches, I may only want the label to be 0.175 inches wide, so I need the space to fit the characters.

What's the different script you found that runs in a palette? Link?

I've read that the palette isn't as widely supported and dialogs are more the way to go.

**Comment by schroef** [comment]
Ah Okay thanks for clearing that. I always use dialog when making scripts. I also hardly see palette used in any script. There is another option I believe, is that windowless?

I'll try your version layer tonight but I got a feeling it wi crash as well. Ps how did you add all the functionality in? I basically pasted all button functions and another functions below that script from the website. Added all vars at the beginning. That way it's sort of easy to swap scripts if needed. Not sure everything works properly though.

Ah so you work in inches, that explains. Well I guess you old setup was to narrow then. Those had just 3 characters. I think default is about 3, most Adobe windows also have about 3 wide.

**Comment by schroef** [comment]
Ps does the horizontal tab version work properly for you, what illustrator are you using?

**Comment by adamdehaven** [comment]
Horizontal works fine for me. I have CC 2019 and CC 2020

**Comment by schroef** [comment]
ah nice, yeah its a shame i cant upgrade due to my old system :(

I found that script here https://github.com/Silly-V/Experiments
He has a couple more super nice scripts. Also that recolor thing i mind-blowing!!!

Look how tiny this window is for his version. Super nice! Though it looks kinda retro because of that logo hahaha, that's actually an SVG he embedded. WHat i also like in this version is the option of different line styles. I had been thinking about that as well. He adds them by using predefined lines he setup inside the script. They even update their color when you pick a pre-defined color. One thing i don't understand is that option to capture size. Not sure what the intention of that is

![Screen Shot 2020-05-15 at 7 54 25 PM](https://user-images.githubusercontent.com/6923008/82104812-53280e80-96e6-11ea-90ea-4d4c90971b55.png)
![Screen Shot 2020-05-15 at 7 59 18 PM](https://user-images.githubusercontent.com/6923008/82104886-9edab800-96e6-11ea-93d1-17e1bdf3645b.png)


Here's how that panel would look, its super minimal compared to the dialog. 
![Specify-Horizontal Tabs-06-3](https://user-images.githubusercontent.com/6923008/82104659-bebdac00-96e5-11ea-89f1-67ce2c37802e.png)


![Specify-Horizontal Tabs-06-1](https://user-images.githubusercontent.com/6923008/82104657-bd8c7f00-96e5-11ea-95d2-94edaef5162e.png)
![Specify-Horizontal Tabs-06-2](https://user-images.githubusercontent.com/6923008/82104658-bebdac00-96e5-11ea-90d1-8ab2d84e4838.png)

**Comment by schroef** [comment]
PS i noticed you added folders now, is that a common for these scripts? I would thing we should at least name the folder with something with specify, i know vendor is common for 3rd party parts. PS i also renamed the picker.js file to colorpicker.inc that way it does show the script when you load the script. Thats also how Photoshop does it for helper scripts. The script will still run when its being imported.

**Comment by adamdehaven** [comment]
The folders are for the README.md images, and for now, for the colorPicker.js vendor script (temporary location).

I'm not sure what you mean by this:

> that way it does show the script when you load the script. Thats also how Photoshop does it for helper scripts. The script will still run when its being imported.

**Comment by schroef** [comment]
Sorry if i wasnt clear enough. What the colorPicker file ends with inc, is so it wont show from the script file menu but still runs. If it keeps the JS extension it will show in the script menu and a user perhaps could things its usable as standalone.

I noticed this being done in PS script, I thought it was handy.

**Comment by adamdehaven** [comment]
Resolved with v2.0.0

**Comment by adamdehaven** [comment]
@schroef I just released the script as an official Adobe extension as well! [Feel free to download it from Adobe Exchange](https://exchange.adobe.com/creativecloud.details.104123.specify.html)! 🎉

**Comment by schroef** [comment]
Wow that's very cool man! I was also thinking of trying it but I didn't find the time yet. Will try it!!!

Ps if your thinking about adding localize, I've tested this for a different extension and got it working. It's a lot of work but really helps users something. At least it's nice to see it in your own language

**Comment by schroef** [comment]
Ps is it me or does it look like a script window? Or did you use same design?

**Comment by adamdehaven** [comment]
What's your primary language?

**Comment by schroef** [comment]
My primary language is Dutch, but i have all my apps on English. I prefer this so i can find stuff easier when i need to do some Google work.

PS i tried installing the manual way with Anastasiy Extension Manager and i got an license error.
Ill check if updating that manager helps
![Screen Shot 2020-06-17 at 9 57 09 PM](https://user-images.githubusercontent.com/6923008/84969096-fdc88e00-b0e5-11ea-9b62-fc0716b79179.png)

**Comment by adamdehaven** [comment]
I haven't been able to install anything with that extension manager without receiving the same license error. I think it's flawed

**Comment by schroef** [comment]
I did try ZCP with which i get more luck most of times. I got an error about a license as well, but not the same.

![Screen Shot 2020-06-17 at 10 10 28 PM](https://user-images.githubusercontent.com/6923008/84969827-7b40ce00-b0e7-11ea-9cb5-2049405fdbf9.png)

I just checked errors codes for Exchange extensions. Ill download it again and see if that helps
https://helpx.adobe.com/uk/exchange/kb/error-codes.html
![Screen Shot 2020-06-17 at 10 13 53 PM](https://user-images.githubusercontent.com/6923008/84970048-eb4f5400-b0e7-11ea-85d8-b2babfcf0694.png)

**Comment by adamdehaven** [comment]
Let me know how it goes. I can take a look tomorrow. It should install fine from CC and the link I provided.

**Comment by schroef** [comment]
Yes i know but i also try other options. Ive tried another ZXP installer. I got like 3 of them. UberManager also gave an error with the file. Ive also downloaded again, same issue

**Comment by schroef** [comment]
I got it installed but it doesnt show in my older illustrator. I tried everything i know about these panels and did changes accordingly. Still panel wont show in the extension menu.

PS one thing i noticed, in the manifest file, you have named it "com.adamdehaven.Specify.Extension" but does that actually work for you? Because according to everything i read, there are 4 types . These are: Panel, ModalDialog, Modeless & Custom. I would think adding that Extension already is one issue. I always tend to add that to the ID name as well. So I'm probably mistaken on this part. I tried lowering the CEP to 7 and added CEP7 script. Still nothing?

But i guess it did show for you otherwise you wont release it.


![Screen Shot 2020-06-18 at 12 45 39 AM](https://user-images.githubusercontent.com/6923008/84979406-653e0800-b0fd-11ea-8701-fb3d10d5470e.png)
![Screen Shot 2020-06-18 at 12 43 26 AM](https://user-images.githubusercontent.com/6923008/84979412-67a06200-b0fd-11ea-8f0c-a5fe24903538.png)

**Comment by schroef** [comment]
Okay i got it working, off that took a while. Its something related to the paths. Its so confusing all the different method of paths in the different coding languages.

Works nice and weird things is, even though i think its still a script. The horizontal panel doesn't crash now for me like it used to do. Quite weird huh?

I still hope to make the real panel i had in mind. Meaning, everything is visible in the extension panel, this no need to click a buttons twice.

Did you had any experience with making such a panel. I find it quite bizarre how much code is involved in something with is that simple. If you think about it ;)

**Comment by schroef** [comment]
PS i did notice a difference in your version vs my version for the HEAD & TAIL size. If use both scripts and set them both to the default. Mine are bigger then yours somehow??

If i then check the size of them, they seem to divided in half? Same is for the gap size

Top one is my version of the script, gap & heal&tail size are correct of what i input. In your version they are around half of that input size.

![Screen Shot 2020-06-18 at 2 25 52 AM](https://user-images.githubusercontent.com/6923008/84985752-56f6e880-b10b-11ea-8214-fb117858392b.png)

**Comment by schroef** [comment]
Another detail i found, the button to github gives me this weird address, same as for the website link ```file:///.file/id=6571367.13548776```

In the panel i did some work on, URL are done with the csinterface
``` csInterface.openURLInDefaultBrowser("http://www.sbaril.me/links"); LoseFocus();```

**Comment by adamdehaven** [comment]
There's an updated version 2.0.1 that is awaiting approval. I received the same license issue when trying to install through one of the extension managers instead of through Creative Cloud for v2.0.0, but that issue seems to be resolved with the v2.0.1 version that is pending. 

@schroef so you're saying the GitHub link in the panel didn't work for you at all? I create the link via a file path, which then redirects to GitHub (this should allow support for older versions of Illustrator). Did the link work for you at all?

Otherwise, I can try updating to the link structure you have above.

**Comment by adamdehaven** [comment]
@schroef **UPDATE**: I tested the `csInterface.openURLInDefaultBrowser` method you suggested, and have updated the extension accordingly. v2.0.2 has this fix; the official Adobe Extension is pending but it should be implemented there in the next couple days.

**Comment by schroef** [comment]
The link did not work on my old illustrator, it show the path like I mentioned earlier. Weird thing is the script looks okay. Seem like a general supported method for jsx files to get urlpath.

I did lower the cep to 7 in my tests.

I tried some other plugins and many actually have install issues with the license. Perhaps that because some were quite old. That should not be an issue with yours. I've never tried that license part before. I did it once with that zxp license app you can get at cep GitHub, but I used fake input and seemed to work. 

Do you need a paid account or something to get it on Adobe exchange?

**Comment by adamdehaven** [comment]
> Do you need a paid account or something to get it on Adobe exchange?

When you download from Adobe Exchange it installs through the Adobe CC app on your computer, so possibly

**Comment by schroef** [comment]
Nsorry iwasnt clear. I meant for being a developer. I was just curious if you need to Ake say payment to have some kind of license key attached to your extension

**Comment by adamdehaven** [comment]
Nope, it's free.

**Comment by schroef** [comment]
@adamdehaven 
Hi adam, been a while. Hope all is fine with you. I got something nice perhaps. Im working off and on on a extension for photoshop and was investigating the again how to use a color picker. I know now how we can call the native color picker.

Are you interested in the code? I know you already the other implementation i found and the colorwheel is actually very nice. I was just thinking of this add no since we did quite some work to get this working properly.

**Comment by adamdehaven** [comment]
@schroef if you want to fork a fresh copy and create a new PR, I'll be happy to take a look in the next couple weeks over the holiday. 

Just try not to add any extra changes other than the single change for now so I can see what you've got in mind 👍

**Comment by schroef** [comment]
I just got a Windows machine :) loo so much to learn after 17yr osx I'm not fully setup yet. 

Can I also show example code of how to call the color picker? I found the code in one of photoshoots scripts. Have not test it yet if it also run on illustrator
