### ISSUE TITLE
Label scaling

### ISSUE THREAD

**Issue by dhighet** [adamdehaven/Specify#2]
Firstly thank you so much for this. I've been in need of a script like this for a long time.

Would there be a way to increase the size the labels? Or even take into consideration of working at different scales? I typically work in a fairly large format so typically things will be a 10th of their actual size (so something that is 24", will read in AI as 2.4").

Thank you!

**Comment by adamdehaven** [comment]
There are a couple places where you can modify the code in the `Specify.jsx` file to accomplish what you're wanting:

To increase the font size, change the value of line `284`, to whatever size works best for your typical use case:

```
t.textRange.characterAttributes.size = 8; // Default is 8
```

You can also change the default spacing for measurement lines, as well as the number of decimals in the measurement, and pixels per inch on lines `55` - `64`:

```
// gap between measurement lines and object
var gap = 2;

// size of perpendicular measurement lines.
var size = 6;

// number of decimal places in measurement
var decimals = 3;

// pixels per inch
var dpi = 300;
```

If you have other suggestions/questions, feel free to open another issue or comment on the [project's page on my site](http://adamdehaven.com/blog/2015/05/dimension-adobe-illustrator-designs-with-a-simple-script/)
