### ISSUE TITLE
Extension retracted error

### ISSUE THREAD

**Issue by krmnelson** [adamdehaven/Specify#20]
Hi! I have been using Specify with Adobe Illustrator 2019. I recently upgraded to Adobe Illustrator 2020 and the extension will no longer install. It give an error code and states the extension has been retracted by partner. Can you help me with this?

**Comment by adamdehaven** [comment]
Hey @krmnelson

The extension has changed to a subscription model (only $11.99/year) which supports me being able to devote more time to development, feature requests, and user support.

You can download the [latest version of Specify from Adobe Exchange at this link](https://exchange.adobe.com/creativecloud.details.106345.specify-dimensions-and-measurements.html).

There is also a new site with docs and other info [specify.dehaven.org](https://specify.dehaven.org/?utm_source=github&utm_medium=issue&utm_campaign=subscription_launch)

I hope this helps! Let me know if you have any issues.
