### ISSUE TITLE
Error Window when adding dimensions

### ISSUE THREAD

**Issue by fubar2fixed** [adamdehaven/Specify#21]
Users are getting this error window/message when creating dimensions using the Specift Script in Illustrator, the folder is located at  C:\Program Files\Adobe\Adobe Illustrator CC (64 Bit)\Presets\en_US\Scripts as required.

specify error => toggle Specify Dialog: IOError: File or folder does not exist

**Comment by adamdehaven** [comment]
@fubar2fixed was the extension installed through Adobe Exchange?

**Comment by fubar2fixed** [comment]
@adamdehaven it was not, the version of Illustrator we're using was too old to use the Extension for the Exchange so we installed the script manually.  We will need to use it this way as a temporary solution until our press is updated and we move to the new Adobe CC that will support the Exchange.

**Comment by adamdehaven** [comment]
@fubar2fixed it should still work; you may need to look at the folder location. For example, for my current install of Illustrator, the folder is located at `C:\Program Files\Adobe\Adobe Illustrator 2021\Presets\en_US\Scripts`

Regardless, if you know where you saved the Specify folder, you can run it manually with `File > Scripts > Other Script` (or `Ctrl + F12`) and then choose the `Specify.jsx` file.
