### ISSUE TITLE
IO Error: File or folder does not exist

### ISSUE THREAD

**Issue by fubar2fixed** [adamdehaven/Specify#24]
![Specify Error](https://user-images.githubusercontent.com/83237385/125632798-be71f821-072e-45c2-a1ce-e848b174952d.PNG)
![SpecifyInstallLocation](https://user-images.githubusercontent.com/83237385/125632799-db0ca486-c3a6-4f41-8513-97d2f60be6cb.PNG)

We have one Windows 10 PC that the script doesn't seem to work for in our old version of Illustrastor, we are using the same files on 5 other Windows 10 PC's with the same version of Adobe CC without issues.  I have even tried downloading a new copy of the script and re adding it to specified folder.

**Comment by adamdehaven** [comment]
What version of Adobe Illustrator is the non-working computer running? It's hard for me to help troubleshoot the older versions of the plugin as Adobe has updated some of the dependencies depending on what version you're running.

It looks like you're trying to use an old version of the Specify script `3.2.0` -- the script has been updated and is [available through Adobe Exchange](https://exchange.adobe.com/creativecloud.details.106345.html) if you'd like to update to the latest version.

**Comment by fubar2fixed** [comment]
Its Illustrator V17.0, which is too old to download it via the Adobe Exchange which is why we're having to use this older version for the next few months until we can update to a newer version of CC.

**Comment by adamdehaven** [comment]
Ah ok. Hmm, I'm unsure why it wouldn't be working for a single instance. It looks like it's hanging on this line, but I can't imagine why as it looks like all the files are there

```
xLib = new ExternalObject("lib:PlugPlugExternalObject");
```

**Comment by fubar2fixed** [comment]
Well it seems to be working again, even with the above error still occurring, hopefully we can keep limping along until our new press arrives and we can finally upgrade everything.  Thanks Adam!

**Comment by fubar2fixed** [comment]
The other users seem to be having the same error pop up but since its been working never said anything so it must be something Adobe changed.
