### ISSUE TITLE
Possible to get fractional inches?

### ISSUE THREAD

**Issue by billetandsons** [adamdehaven/Specify#25]
I know it's not built in AI, have to deliver architectural measurements and fractional inches are all the rage there.

thanks!

**Comment by adamdehaven** [comment]
@billetandsons so essentially what you're asking for is to be able to display `1 3/4"` instead of `1.75"` - is that correct? 

Also, what's the proper way to display the measurement? For example, would you show `1 3/4"` or `1-3/4"`, etc.?

**Comment by billetandsons** [comment]
thanks @adamdehaven!
Correct for 1 3/4". 
They also write it as a "classic" fraction (numerator OVER denominator) but I guess this would be font/glyph dependent.
numerator/denominator would work.

here's a [ref ](https://www.dropbox.com/s/issoj4zl9rtlgvk/Dims.jpg?dl=0) from a drawing. From what I gathered the Dash is a convention but if there would be optional it will be sweet.

cheers

**Comment by adamdehaven** [comment]
> They also write it as a "classic" fraction (numerator OVER denominator) but I guess this would be font/glyph dependent.

@billetandsons - correct, this would be font dependent (and most do not support fractions) so it would be output as `numerator/denominator`.

I've pieced together a way (still testing) to reliably do the conversion. This is going to sound like a weird ask, but can you give me some example decimals and their corresponding fractions (i.e. give me a list of the ones that are common for you). Just give me a list like shown below; however, it would be helpful if you provided some examples that were a little more complex than what I'm showing:

| decimal | fraction |
|----------|----------|
| `.25` | `1/4` |
| `.3334` | `1/3` |

**Comment by billetandsons** [comment]
handy cheat sheet
[DB](https://www.dropbox.com/s/otm31sn89y5yu22/Decimal.jpg?dl=0)

depending on the scale, I don't think they go smaller than /16th.

**Comment by adamdehaven** [comment]
Pasting here for reference
![fraction cheatsheet](https://user-images.githubusercontent.com/2229946/134723929-412f77a0-8a91-41e5-90b3-00072c216ad3.png)

**Comment by billetandsons** [comment]
Like in the chart, the intervals used are 1/4s, 1/8th, 1/16th and 1/32th

**Comment by adamdehaven** [comment]
So the problem I'm running into:

If I try converting `0.0156` into a fraction, I'm getting `10/641`; however, if I convert the whole decimal of `0.015625` I properly get `1/64`. Still trying to figure out the rounding.

**Comment by adamdehaven** [comment]
@billetandsons so does this look like what you're wanting?
![specify extension using fractions for measurements](https://user-images.githubusercontent.com/2229946/134731978-51ffaf87-aaed-4e6a-a163-5f3c8d52973e.png)

**Comment by billetandsons** [comment]
Yes Chef! This is wicked. Just what I needed. 
I usually relent to this chart
https://www.engineeringtoolbox.com/inches-decimal-equivalents-d_471.html
and round up.
Usually it's for builds (like extruded logos) that are 6-8 feet wide so /16th inch is a good enough to round.

**Comment by adamdehaven** [comment]
I’ve got this working and have been running through some test cases. 

I’m planning to provide a “maximum denominator” field that allows the user to set the maximum denominator for the fraction which impacts how the rounding algorithm interprets the measurement (the default will be `64`).

**Comment by adamdehaven** [comment]
@billetandsons one request: Would you be willing to provide me with a sample Illustrator `.ai` file with a series of example objects that would use fractions in the measurements? You don't need to run the extension, just provide me properly sized objects on the artboard. 

I can run the fraction-enabled script on the file and compare the results with what you are expecting. I'd really appreciate it!

**Comment by billetandsons** [comment]
Hi Adam, unfortunately I can't share a specific file from our project as it's still under production, So I changed the logo on the sign.
What happens is we CNC our letters and then need to make a diagram for the construction team on how to mount the letters to the backing - 
Specifying the distance of the letters from the edge of the sign.

[Specify Sign.zip](https://github.com/adamdehaven/specify/files/7230083/Specify.Sign.zip)

**Comment by adamdehaven** [comment]
@billetandsons even if you could just make a test file (remove any proprietary info) it would be greatly appreciated

**Comment by billetandsons** [comment]
Here's something that was produced and measured by hand, including my dims.

[PayDay Sign.zip](https://github.com/adamdehaven/specify/files/7230217/PayDay.Sign.zip)

**Comment by adamdehaven** [comment]
@billetandsons thanks for all of your help! I have just submitted version `4.3.0` for review to Adobe Exchange and it should be available later this week. Once released, you should see the update available in the Creative Cloud desktop application under **Marketplace** `>` **Manage plugins**

One note: when using fractions, you may have to play around with the Maximum Denominator setting to get the level of rounding/approximation you desire (i.e. if the fraction doesn't match what you are expecting). 

![fraction max denominator](https://user-images.githubusercontent.com/2229946/134925294-ced3c5c1-bfe6-4f7c-a957-b57a84766320.png)

For example, if you have a dimension that returns a large denominator but you are expecting something like 1/3, try lowering the maximum denominator value to something like `10`.

**Comment by billetandsons** [comment]
@adamdehaven thank you! It would be great.
To confirm - can the measurement return any denominator? When specifying fractional inches, 
the convention is 1/2 - 1/4 - 1/8 - 1/16 - 1/32. Something like a 1/3 won't work in inches world

**Comment by adamdehaven** [comment]
@billetandsons the maximum denominator setting can take any value from `1` - `999`. The algorithm cannot explicitly do math "in inches" meaning that it may return fractions that are not in your conventional measurement set. 

For example, if you were to have an object that measured `1.3333` inches on one side, it will likely return `1 1/3`.

**Comment by billetandsons** [comment]
I see. Is there a way to define ranges for decimals, based on a table like this
https://www.engineeringtoolbox.com/inches-decimal-equivalents-d_471.html

so any fraction can be defined to a specific range and matched withing this range to the nearest fraction?

**Comment by adamdehaven** [comment]
> I see. Is there a way to define ranges for decimals, based on a table like this: https://www.engineeringtoolbox.com/inches-decimal-equivalents-d_471.html

Again, no, because this only accounts for inches and I coded the fraction feature to work with other units as well.

I believe you'll see once you play around with the updated extension that you should be able to get what you're wanting for the most part (assuming you create objects at the correct dimensions). If you look at the screenshot below, I was able to get the correct dimensions from the table you referenced while leaving the `maximum denominator` setting at the default value of `64`.

![object with decimals and fractions](https://user-images.githubusercontent.com/2229946/134960750-213fc0a2-8d13-4eff-b8e5-63c7b7cdd6e0.png)

**Comment by billetandsons** [comment]
got it. ! I'll test the updated extension when it lands.
once again - massive thanks for the speedy reply and updates.

**Comment by adamdehaven** [comment]
@billetandsons version 4.3.0 is now available if you update via the CC desktop app. Let me know how it goes
