### ISSUE TITLE
Issue with Specify panel too large for window

### ISSUE THREAD

**Issue by zemel2** [adamdehaven/Specify#26]
I can open Specify but I cannot move it on my screen to grab the preferences.  Can you please assist.

**Comment by adamdehaven** [comment]
@zemel2 I'm happy to help.

Can you provide me with a screen recording or some screenshots to help me understand what's happening?

**Comment by zemel2** [comment]
This what appears.  I can’t move it to get to the settings.  It stays fixed on my screen.

 

I don’t know if it’s a bad install.

**Comment by adamdehaven** [comment]
@zemel2 I think you responded via email but the attachments didn’t come through. You’ll need to respond directly on GitHub to include the attachments. 

Alternatively you can reach out on Twitter via direct message if that’s easier: [@adamdehaven](https://twitter.com/adamdehaven)

**Comment by zemel2** [comment]
Can you please assist with me the Specify install.  Essentially, it opens but then locks on the screen.  I can't change the size or move it around.

**Comment by zemel2** [comment]
![image](https://user-images.githubusercontent.com/97308761/149832998-34c98cab-6a47-49f4-9e0d-a07561a35eec.png)

**Comment by zemel2** [comment]
This is how it shows up and I can't pull it down

**Comment by adamdehaven** [comment]
@zemel2 your screenshot really needs to show what you can see on your entire computer screen -- I can't tell what is going on from a screenshot of the extension panel.

This appears to be an issue with the display resolution on your computer which is nothing the extension itself can control. The extension window size is determined by the amount of content within the extension panel.

You should be able to go into your computer's display settings and set a higher resolution and then determine the proper settings in order to utilize the extension. 

If you'd like to provide a screenshot of your entire screen, I can try and help determine what's going on.

**Comment by zemel2** [comment]
![image](https://user-images.githubusercontent.com/97308761/149839083-7988329b-36dd-4c3e-ace1-8c47a0bd0fbe.png)

**Comment by zemel2** [comment]
It shows up as a box and I can't move it up down or sidewways

**Comment by adamdehaven** [comment]
Thanks for the extra screenshot. It looks like the dialog window is larger than your monitor viewport and is getting cut off. 

I'm looking into a permanent fix now, but in the meantime, you may need to alter your display settings in Windows to a higher resolution. By setting your display resolution to a higher pixels per inch, you should be able to view the entire extension panel.

**Comment by zemel2** [comment]
OK.  I reduced the viewable screen to 125% and that seems to work.

**Comment by adamdehaven** [comment]
@zemel2 can you tell me what the setting value was set to previously?

**Comment by zemel2** [comment]
150%.  That's what was recommended.

**Comment by adamdehaven** [comment]
I'm working right now to make the dialog window resizable; I'll comment back here with an update. Thanks for reporting the issue!

**Comment by adamdehaven** [comment]
@zemel2 based on your feedback, I just submitted version `4.5.0` to Adobe for review which "shortens" the height of the extension window. This does cause the window to become a little wider, but most screens are wider than they are tall.

![specify-options-panel](https://user-images.githubusercontent.com/2229946/149855760-e96cb4dc-d66a-4a16-9e63-5a100104a1db.png)

The update has to be approved by Adobe, so I would think it would be available for download by the end of next week, at the latest. I'll come back here and tag you once the update is available. I'd really appreciate if you can try the updated version at that time to let me know if it totally resolves the issue for you (without having to change the display percentage).

Thanks again for submitting the issue!

**Comment by adamdehaven** [comment]
@zemel2 the new version `4.5.0` is now available for download. Give it a try and let me know here if this resolves the issue for you? 

https://exchange.adobe.com/creativecloud.details.106345.html

**Comment by zemel2** [comment]
My computer did an update and I lost this extension.  Can you assist me with reinstalling it?

 

Daniel A. Zemel
FASTSIGNS North Phoenix – Store 2299 | Owner |  ***@***.***> ***@***.***

Cell: 602-799-6382  Office:  602-715-2222

4731 E. Union Hills, Suite 112, Phoenix, AZ 85050

 <http://www.fastsigns.com/> www.fastsigns.com  |  FASTSIGNS  <https://www.facebook.com/FASTSIGNS> Facebook  |  FASTSIGNS  <http://twitter.com/fastsigns> Twitter  |  FASTSIGNS  <http://www.fastsigns.com/Blog> Blog

**Comment by adamdehaven** [comment]
It should still be available via Marketplace, Plugins within the Creative cloud app as long as you’re still signed in to the same Adobe account. 

>
