### ISSUE TITLE
[Bug Report] - Window Size

### ISSUE THREAD

**Issue by Guss7777** [adamdehaven/Specify#27]
**Describe the bug**

After the latest update, the "Cancel" and "Specify Objec(s)" buttons falls off the Specify UI.

**To Reproduce**
1. Launch application Illustrator
2. Select object
2. Run extension
4. See bug

**Expected behavior**

Buttons should show up on UI.

**Screenshots**

[https://www.linkpicture.com/q/Specify.jpg](url)
![image](https://user-images.githubusercontent.com/98779410/151873104-6d4ae7c0-b132-4322-a61c-d028cd36fcb0.png)

**Desktop (please complete the following information):**

Windows 10
Adobe Illustrator CC v26.0.3 (64bit)

**Additional context**

None

**Comment by adamdehaven** [comment]
@Guss7777 thanks for reporting, I'll take a look.

Can you give me some additional info:
- Monitor size
- Display resolution settings
- Windows or Mac (and if Mac, Intel or Apple chip)

**Comment by adamdehaven** [comment]
@Guss7777 I just submitted version `4.5.1` to Adobe for review which should address the issue you're seeing. I'll ping you back here when the new version is available for download.

If you're able to screen share, we can debug further if needed.

**Comment by adamdehaven** [comment]
@Guss7777 version 4.5.1 is now available for download if you want to give it a try: https://exchange.adobe.com/creativecloud.details.106345.html

You should be able to update the plugin via the Creative Cloud Desktop app under Marketplace > Plugins > Manage Plugins

**Comment by Guss7777** [comment]
@adamdehaven The "Specify Objec(s)" button is still not showing. So, I'm just using "enter" at the moment.

![Specify2](https://user-images.githubusercontent.com/98779410/152033641-067f558f-181e-40d6-8871-4944ccba48a1.jpg)

**Comment by adamdehaven** [comment]
@Guss7777 can you provide a screenshot that shows your entire screen instead of just the extension window?

Also, what are your display settings on your computer (e.g. if on Windows, is it set to 150% or something)?

**Comment by Guss7777** [comment]
@adamdehaven Display Settings:
![Display1](https://user-images.githubusercontent.com/98779410/152035616-7004c461-2847-4169-9378-454770a0eec1.jpg)
![Display2](https://user-images.githubusercontent.com/98779410/152035626-ad35a15b-61bd-4d9b-97a5-e8afdd1e34e6.jpg)

**Comment by adamdehaven** [comment]
@Guss7777 can you provide a screenshot that shows your entire screen with Illustrator and the extension window instead of just the extension window?

**Comment by Guss7777** [comment]
@adamdehaven Full Screen
![FullScreen1](https://user-images.githubusercontent.com/98779410/152036127-63352dfb-47e1-4646-992c-2c509c025159.jpg)
:

**Comment by adamdehaven** [comment]
@Guss7777 that is so odd. I can't even reproduce it (thanks for the extra screenshot).

Would you be up for doing a screen share so I can try and debug? 

The only solution I can think of at the moment is to align all of the buttons to the left.

**Comment by Guss7777** [comment]
@adamdehaven sure how would you like to do the screen share? Teamviewer OK?
Left aligned buttons sounds like a good temporary solution. ;)

**Comment by adamdehaven** [comment]
@Guss7777 I'm available now if you are. I can share a Google Meet link when you're ready? (or if you have another way, that's fine. I can delete the link when we're done)

**Comment by adamdehaven** [comment]
Another version `4.5.2` is available now with a few other tweaks to the button layout; wondering if it helps you @Guss7777 -- we can still sync up later today if you'd like.

**Comment by Guss7777** [comment]
@adamdehaven The buttons still look the same. I'm ready for the Google Meet link, if you are.

**Comment by adamdehaven** [comment]
@Guss7777 are you available at 5:30pm Eastern?

**Comment by Guss7777** [comment]
@adamdehaven We can do it now if you'd like.

**Comment by adamdehaven** [comment]
I'm stuck on work calls until 5pm Eastern

**Comment by Guss7777** [comment]
@adamdehaven No probs - that's 11am here... I think. 🤔

**Comment by adamdehaven** [comment]
@Guss7777 Hey sorry I'm available now if you are

**Comment by Guss7777** [comment]
@adamdehaven great let's do it. What do you need me to do?

**Comment by adamdehaven** [comment]
Join here: To join the video meeting, click this link: https://meet.google.com/ubb-hsjr-egc

**Comment by adamdehaven** [comment]
@Guss7777 thanks again for all of your help earlier in debugging this issue! I have version `4.5.3` awaiting Adobe review and release, and I have been able to verify this does fix the issue going forward. I'll ping you once more here when the download is available.

For any Adobe extension developers that stumble on this issue, when creating an extension window with the code shown below, be **SURE** to add `dialogWindow.alignChildren = ["left", "top"]` -- if you use `["center", "top"] ` and the user has Windows display settings scaled to a value greater than `100%` some of your UI elements will be cut-off/hidden from view.

```jsx
const dialogWindow = new Window("dialog", undefined, undefined, {closeButton: true, resizeable: false});
dialogWindow.alignChildren = [ "left", "top" ]; // IMPORTANT!!
```

**Comment by Guss7777** [comment]
@adamdehaven  Thx for getting this all sorted. It's working like a charm now. 😉 👍

**Comment by adamdehaven** [comment]
@Guss7777 glad to hear that the update resolved the issue. 

Thanks again for your help debugging!
