### ISSUE TITLE
Specify has disappeared

### ISSUE THREAD

**Issue by krmnelson** [adamdehaven/Specify#29]
Hi! Specify has disappeared from my Illustrator Extensions folder and no longer shows up in my Plugins in Creative Cloud. I just paid for a renewal also.

**Comment by adamdehaven** [comment]
@krmnelson I'm seeing the same thing as you -- it disappeared from my Creative Cloud app as well; however, it's still available on Adobe Exchange for purchase/download.

I have reached out to Adobe directly to see what is going on as I have not done anything to alter the availability of the Specify plugin.

**Comment by adamdehaven** [comment]
All I can recommend until I hear back is that you try emailing asupport@adobe.com with the issue as well and see if you can get a response faster than I can. 

Unfortunately, they don't give developers much more help

**Comment by krmnelson** [comment]
Hi Adam,

I already tried Adobe Support. They tried directing me to a fix for the
error I was getting, 1001, but the link was for MacOS. I have Windows. I
tried manually installing with the installer mentioned in your info about
Specify. It also gave an error and said to contact you, the developer. The
error said something was corrupted. I can't remember what it was.

Thank you,
Kristi

**Comment by adamdehaven** [comment]
Can you share what info they gave for the `1001` error on Mac? I can try it on my Mac.

I've reached out to another Adobe contact I have; trying to figure this out

**Comment by krmnelson** [comment]
Hi Adam,

Here it is:
https://helpx.adobe.com/in/creative-cloud/kb/installation-update-failure-macos.html#sa_src=web-messaging

Thank you,
Kristi Nelson

**Comment by adamdehaven** [comment]
Ugh... the download button the page doesn't even work.
I tried uninstalling/reinstalling Creative Cloud Desktop app and no luck there either; the same problem.

My Adobe contact reached back out; however, she had to forward the issue to a colleague so hopefully they get back to me tomorrow

**Comment by krmnelson** [comment]
Figures. The troubleshooting links in the email for the renewal of the
plugin didn't work either.

Let me know what you find out. I use the plug in quite a bit.

Thank you,
Kristi

**Comment by adamdehaven** [comment]
I have a temporary workaround you could try but I'd probably need you to screen-share to walk you through it. If that's something that would be helpful, we could sync up Tues or Wednesday. 

Either way, I'll definitely post an update here if/when I get one. 

Based on my Adobe contact's comments, this is not an isolated issue (e.g. Specify wasn't the only impacted plugin)

**Comment by krmnelson** [comment]
Hi Adam,

I am ok for now. If it doesn't get resolved soon, I will get back to you.

Thank you,
Kristi Nelson

**Comment by adamdehaven** [comment]
Update from Adobe:

So, behind the scenes there is now a flurry of emails as this is investigated.

Fortunately the engineers have been able to reproduce this problem, which is promising. (Problems that are not reproducible are much harder to solve....)

 

Both of your plugins are incorrectly throwing some sort of "expired" flag, which causes them to be uninstalled and is also triggering the entitlement error (1001). I don't know where or how this expired flag is generated, but some of the Exchange engineers on Pacific time may be able to tell us.

 

The part where the plugins aren't showing up in the Creative Cloud desktop app seems like a different issue, which might have to do with UXP and sorting. (UXP isn't available for Illustrator yet.)

 

So work is going on behind the scenes! If there's a JIRA ticket (or tickets) I'll track those and report back here.


Thanks, 

Adam

**Comment by krmnelson** [comment]
Ok! Thank you for the update!

**Comment by krmnelson** [comment]
Hi Adam,

Any update on this? I could really use Specify today!

**Comment by adamdehaven** [comment]
I haven’t heard back from them yet today. 

Adam

**Comment by adamdehaven** [comment]
@krmnelson just received an update from Adobe:

Hi Adam,
wanted to send you a quick note and let you know that we are still looking into this, a number of people are working on identifying the root cause.

I appreciate your patience and hope to be able to giving you more details in the next update.

**Comment by krmnelson** [comment]
Ugh! Ok! Thank you!

Thank you,
Kristi Nelson

**Comment by adamdehaven** [comment]
Another update from Adobe:

> We're still investigating the error 1001 issue, it appears to affect people who have previously purchesd plugins (not first time purchasers), something in the system is erroneously firing an "expired" flag.
> 
> The error messages are not helpful in this case. A compatible app is installed, but the user is flagged as not entitled. Customer support is routing users back to the plugin developer, but there's no way for you to fix this. Customer support is following the procedure for the (unhelpful) errror code.
> 
> Illustrator apps (and apparently some, not all) shouldn't be penalized into another section with no purchase button; especially with no explanation of WHY they aren't showing the button. 
> 
> I totally agree with this, and have sent the comments on to the Product Manager of the Marketplace. Unfortunately the Creative Cloud desktop 5.7 app rolled out just before we both went on vacation... Fortunately that means people who haven't updated the desktop app won't see that sorting method.  Hopefully we can fix it before 5.8 rolls out (targeted for June), I'll check on that...

**Comment by krmnelson** [comment]
June! We don't have the option not to update the desktop app. It is
automatic and updates almost daily.

Kristi

**Comment by adamdehaven** [comment]
June is referring to why the plugin isn’t listed in the proper section. From my understanding, the install/usage issue is being worked on ASAP 

Thanks, 

Adam

**Comment by krmnelson** [comment]
Ok.

Thank you,
Kristi Nelson

**Comment by adamdehaven** [comment]
@krmnelson 

Update from Adobe:

---

We've been investigating the entitlement issue and there's a temporary fix in place while the root of the problem is addressed. (I'm told that the temporary fix will appear permanent for end users.)

 

Apparently, only users with auto-renewing subscriptions were affected. Please ask your customers to try reloading your plugin from within the Creative Cloud desktop app and let us know if it works.

 

The customer support team has been informed of this as well, so hopefully you won't keep getting complaints routed to you. Let us know if you do!

**Comment by krmnelson** [comment]
Hi Adam,

Yes! And it works! Thank you!

Thank you,
Kristi Nelson

**Comment by adamdehaven** [comment]
Great, glad that worked for you! This was a surprisingly fast turnaround for Adobe

**Comment by krmnelson** [comment]
Oh my goodness. That is not reassuring.

Thank you,
Kristi Nelson
