### ISSUE TITLE
Multiple Labels, Single Command

### ISSUE THREAD

**Issue by hyraxx** [adamdehaven/Specify#3]
Ability to add label on more than one side at a time, would be awesome

**Comment by adamdehaven** [comment]
@hyraxx There are times when I only want the dimensions of one side, so this would have to be an option to "dimension all" or something similar.

**Comment by hyraxx** [comment]
Maybe have it as a check box next to each side

**Comment by adamdehaven** [comment]
This could work if a single object is selected, but not for two objects. I'll look into it :)

Leaving the issue open while I research (also gives me time to think of the cleanest UI)

**Comment by yuusuf-sallahuddin** [comment]
I have just done some playing around with the JSX and implemented the Top/Left/Right/Bottom as checkboxes to enable doing all 4 at the same time (or any combination of).

Works for Single or Double objects (although double objects just does the same thing twice, e.g. Top/Bottom gives same result, just placed in different location & Right/Left gives same result, again just placed in different location).

Find edited JSX here (as a text file, change file extension to .jsx). Couldn't upload zip file for some reason.
[Specify - Edited.txt](https://github.com/adamdehaven/Specify/files/504493/Specify.-.Edited.txt)

**Comment by adamdehaven** [comment]
@hyraxx: I'm using @yuusuf-sallahuddin's idea as a jumping-off point and I think I have a pretty clean solution. I'll further test tomorrow... stay tuned.

**Comment by yuusuf-sallahuddin** [comment]
@adamdehaven I've further played with things & added the option to rotate the vertical axis-text (again via checkbox) because sometimes it fits nicer that way (in my cramped patterns), other times it fits better with the text displayed horizontally. Would be nice also if we could also select the font-size from the window when we Specify the object/s. Not adding as a new issue, as it's just suggestions :)

**Comment by adamdehaven** [comment]
@yuusuf-sallahuddin upload your text rotation and I'll take a look

**Comment by adamdehaven** [comment]
@hyraxx @yuusuf-sallahuddin Complete! Check out all the improvements in [version 1.1](https://github.com/adamdehaven/Specify/releases/tag/v1.1)

**Comment by yuusuf-sallahuddin** [comment]
Totally forgot about this & haven't logged into github in a while. I'll check out the improvements in the new version :) Thanks heaps for the update & work @adamdehaven

**Comment by yuusuf-sallahuddin** [comment]
[Specify.jsx.old.txt](https://github.com/adamdehaven/Specify/files/713085/Specify.jsx.old.txt)

Here is my old version that had the option to rotate (or not) the vertical text. A very clumsy attempt at it anyway.

**Comment by adamdehaven** [comment]
@yuusuf-sallahuddin I played around with the rotated text but received feedback (well, from the people I work with that use the script daily) that thought 9/10 times they'd prefer the vertical, so I didn't implement. Thanks for posting the old version though for anyone that stumbles across this issue via search 👍

**Comment by yuusuf-sallahuddin** [comment]
@adamdehaven It's very rare that I would use the text for the vertical axis rotated on a horizontal aspect also, just sometimes when I created Specify on objects, the text created was longer than the object's height. I guess, sometimes it would be the same with horizontal axis text being wider than the object's width too.
