### ISSUE TITLE
Pre-purchase question: UI customization

### ISSUE THREAD

**Issue by keithrussell42** [adamdehaven/Specify#30]
Sorry for opening an issue for this. I couldn't figure out a better way to ask. 

1. I had tried a different extension for dimensioning but it had a non-customizable UI. I prefer to have my Illustrator UI a bit lighter than some others so it was annoying. Luckily it had a free trial so I was able to cancel the subscription. So does this extension's UI follow the Illustrator UI settings (brightness, scale)? 
2. I'm also a little confused on what happens if I apply dimensions to an object then change that object. Do I then have to reapply the dimensions?

**Comment by adamdehaven** [comment]
> 1. I had tried a different extension for dimensioning but it had a non-customizable UI. I prefer to have my Illustrator UI a bit lighter than some others so it was annoying. Luckily it had a free trial so I was able to cancel the subscription. So does this extension's UI follow the Illustrator UI settings (brightness, scale)? 

This follows the UI light/dark settings

> 2. I'm also a little confused on what happens if I apply dimensions to an object then change that object. Do I then have to reapply the dimensions?  

Yes, if the object changes you'd need to delete the outdated specs from the SPEC layer.

**Comment by keithrussell42** [comment]
Perfect. Thank you.

**Comment by adamdehaven** [comment]
@keithrussell42 let me know if you run into any issues 👍🏻
