### ISSUE TITLE
[Feature Request] Simple area calculation

### ISSUE THREAD

**Issue by GerPapa** [adamdehaven/Specify#32]
**Is your feature request related to a problem? Please describe.**
No problem no - been using an older version of your code for years and just discovered it has been updated, so I purchased the new extension.
I use it to dimensions graphics in order to create proof/size verification screenshots for clients
The items I sell are priced by the area of the design - so I multiply the height and width your tool spits out and manually add a text box that states "12 square inch stamp size" for example

**Describe the solution you'd like**
Would be amazing if there was an option to check where the code would take the two dimensions, multiply them together, and then adds a simple text box with the calculated area along with the dimensions it already does
Could have a similar "decimal places" specification and/or custom units text

**Describe anything you've already tried**
There is another extension that appears to calculate an exact area based on complex paths, curves, whatever area the design "covers" -  that is not necessary in this case. Just a simple multiplication of the overall height and width.

**Comment by adamdehaven** [comment]
@GerPapa thanks for the suggestion! 

I think this would be fairly simple to implement, although, I'd need to think of how best to lay out the option in the popup UI. 

I should have some spare time this weekend or next so I'll take a look and see what I can come up with. 

Thanks again (and if you're now using the latest version, any updates will be pushed out via the Creative Cloud app)

**Comment by adamdehaven** [comment]
@GerPapa I've added the feature you have requested in version `4.6.0` which was just submitted to Adobe for approval. The label placement may be tweaked a little in the future; however, for now it places the area label directly in the center of the object.

Here's what the option looks like in the Options panel

![image](https://user-images.githubusercontent.com/2229946/188514143-0530a7ee-c54f-4556-898c-94eb2f9b6149.png)

This should be released sometime next week, pending Adobe's timing on approvals (they are currently backlogged).

**Comment by GerPapa** [comment]
Just got the update -
Amazing, thank you so much!
-Ralf
