### ISSUE TITLE
No clear way to cancel subscription to plugin through Adobe Marketplace

### ISSUE THREAD

**Issue by FastsignsIssaquah** [adamdehaven/Specify#36]
Need instructions on how to cancel subscription to Specify product. No longer want to continue using the app.

**Comment by adamdehaven** [comment]
Sorry the plugin isn't meeting your needs. 

You can manage subscriptions via Adobe's Creative Cloud desktop app. For additional support, you'll need to reach out to Adobe directly as developers have no access to subscriptions.
