### ISSUE TITLE
Straight Quotation Mark [ " ] instead of [ in ] abbreviation for 'inch' unit in UnitValue object

### ISSUE THREAD

**Issue by detra** [adamdehaven/Specify#4]
Thank you for your great script,
was looking to change/insert the 
abbreviation of " in"  to the abbreviation of **"**. 
Using the method of escaping the straight quotation mark " \""

On Line 304 
`case RulerUnits.Inches:
  v = new UnitValue(v, "pt").as("in");
  v = v.toFixed (decimals);
  unitsLabel = " in"; // add abbreviation
break;`

I switched out to

`case RulerUnits.Inches:
  v = new UnitValue(v, "pt").as("in");
  v = v.toFixed (decimals);
  unitsLabel = " \""; // add abbreviation
  break;`

**Comment by adamdehaven** [comment]
I can confirm this works properly as an easy method of modifying one of unit abbreviations. Closing issue (as it's not a bug or issue), but good info for anyone else looking to modify the script in a similar way. Thanks!

**Comment by detra** [comment]
Happy to share and add to your fine script
