### ISSUE TITLE
Distance between centre of 2 objects

### ISSUE THREAD

**Issue by yuusuf-sallahuddin** [adamdehaven/Specify#5]
First up, great project :)

My issue that I would like to see is to have the ability to determine the distance between centres of 2 objects (e.g. 2 circles).

**Comment by adamdehaven** [comment]
Calculating the center of an irregular object would be more complex than the script currently allows.

As an alternative, you could temporarily add a point to the center of each object, use the Specify script to get the dimension, and then remove the points while leaving the dimensions on the SPEC layer.

**Comment by yuusuf-sallahuddin** [comment]
Thanks Adam. That's basically what I have been doing since finding your awesome addon. Note: I posted a fix in the Issue 3: https://github.com/adamdehaven/Specify/issues/3 for the doing Multiple Dimensions at once.

**Comment by adamdehaven** [comment]
@yuusuf-sallahuddin Thanks! I'm taking a look at #3 now
