### ISSUE TITLE
[Feature Request] Specify colors

### ISSUE THREAD

**Issue by adamdehaven** [adamdehaven/Specify#8]
Based on feedback from @KevinConsen in #6:
> Any chance you could make a similar script, or adjust this one, to allow defining colors in a similar way?  Something resulting in:
> 
> ![screen shot 2016-11-11 at 09 59 22](https://cloud.githubusercontent.com/assets/6752605/20209767/65054e20-a7f6-11e6-8a2e-9a150e014759.png)

_(Splitting into separate issue to work separately)_

**Comment by KevinConsen** [comment]
If it's any help, I can help you brainstorm on how to do something like this.. I have some programming knowledge, but wouldn't be able to write it myself. But perhaps I could serve as a stepping stone to a solution? I'm willing to help any way that I can =]

**Comment by adamdehaven** [comment]
Sure thing, I'll keep you posted. With the holidays coming up, it might be a bit before I have time to dig in

**Comment by KevinConsen** [comment]
Maybe it helps.. When I added:

`alert('The color is' + ' ' + doc.selection[index].fillColor);`

in the object at rule 249 ( // Add all selected objects to array) and then ran the script it would pop up the alert and tell me " The color is [CMYKColor]" I'm not quite skilled enough to 'push' any further and internet hasn't been too helpful because I don't know what to google for.

But it seems to be 'close'

**Comment by KevinConsen** [comment]
Hi @adamdehaven ,

Hope you had a great holiday season. Any word on my suggestions? Or any way that I can be of help?

**Comment by adamdehaven** [comment]
@KevinConsen I initially looked into implementing something along these lines back when you opened the issue, but to be honest, haven't had much time to look into it since (holidays, work, life, etc.). I do **very much** still think this would be a great add, and as such, have left the issue open. 

The biggest usability issue I ran into when playing around with this idea is what to do if an object has multiple colors (e.g. a fill color, and a stroke color) or if the color profile being used (CMYK, RGB, etc.) changed or wasn't consistent. If you find anything else similar/helpful, please feel free to update this issue. 

I may have some time in the coming months to look into it. Also, I'm thinking of porting something similar over to Photoshop as I've had lots of requests.

**Comment by KevinConsen** [comment]
I'd say, at least as a start, just report back the fill color. I don't think that there will be a whole lot of object with a fill color and a stroke if you're using this to specify a design.... And it would be a great start.. Or perhaps specify them separately? I can help you figure out a visual way of how to display it if you'd like and make you an example?

**Comment by yuusuf-sallahuddin** [comment]
That is a great idea for an added feature. I am curious how it would work with gradients or pattern fills. I guess you could maybe just report the particular swatch ID or something like that.

**Comment by adamdehaven** [comment]
@yuusuf-sallahuddin things like that use-case is what I'm having trouble with. Without looking deeper so far, I feel like the only way to implement this (cleanly) would be to only allow if the object has a single fill color, which somewhat defeats the purpose.

**Comment by KevinConsen** [comment]
@adamdehaven I'd say that would be a great start. Especially nowadays. A whole lot of designs, especially in illustrator, are single color (material design and other styles). So just being able to specify the (single) fill color would be great and then later find a way to expand.

Also perhaps a similar feature for Fonts? Size, font type, color etc?

I'm very much looking forward to being able to specify colors! If there's anything I can do to be of help, let me know.

**Comment by KevinConsen** [comment]
Hi @adamdehaven 

Any progress on this feature :D?

**Comment by adamdehaven** [comment]
I did recently add the ability to configure the scale of the drawing and modifying the labels accordingly. The color addition you've requested has proven a little more difficult. Still looking into it when time allows.

**Comment by alexleitte** [comment]
First, it was a very good job! Thank you, guys!

In my opinion, would be great if we could choose a swatch color that already exists in the document, like a TECHNICAL COLOR.

**Comment by adamdehaven** [comment]
@alexleitte You can easily change the color of the spec layer by selecting all elements in the layer, and just update the color as desired.

**Comment by alexleitte** [comment]
> @alexleitte You can easily change the color of the spec layer by selecting all elements in the later, and just update the color as desired.

Yeah... I know that... it's just an idea to increase your project into something closer to CadTools, for example.

**Comment by schroef** [comment]
I got a nice color picker working now :)

![added-colorpicker](https://user-images.githubusercontent.com/6923008/81629674-b1e14580-93d1-11ea-89ef-573a4276af8b.gif)

**Comment by adamdehaven** [comment]
Stale. Will reopen if I have time to research or if anyone wants to pitch in.

**Comment by adamdehaven** [comment]
@KevinConsen I’m going to reopen this issue and look into it in the near future. I’ve figured out some new functionality and specifying colors would fit in well.
