### ISSUE TITLE
Font size not based off units

### ISSUE THREAD

**Issue by yuusuf-sallahuddin** [adamdehaven/Specify#9]
I've just given the new improved version a test & found that when using the advanced features & setting the font size to 20, it doesn't make it 20 of the units I have set in my preferences (I almost always work in mm). So in my test case, it sets it to 20 px (maybe?) rather than 20mm.

I wonder is it possible to have it set the font-size to either:

a) auto-detect the units from default font units in the AI preferences
b) auto-set the units to whatever your ruler units is
c) allow it to be selected from a dropdown list of possible unit types

On a side note, I'm super happy with the new UI & features available. Thanks for your work on this project.

**Comment by adamdehaven** [comment]
Good catch (I think)... 

I have an easy fix but may not have time to look into it until over the weekend. Stay tuned

**Comment by adamdehaven** [comment]
After looking into it, it appears your Illustrator settings control the units that the font size box uses. See the screenshot below:
![illustrator-units](https://cloud.githubusercontent.com/assets/2229946/22088140/f660d1d4-ddaf-11e6-93c4-a8beb1f8911e.PNG)

In my case, I use pixels for my document, pixels for object strokes, but have **Type** set to points. If you navigate to **Preferences** > **Units** within Illustrator you can ensure that the setting matches your desired behavior.

I'm going to look further into overriding this setting based on the document's current units, but for now, this works consistently.

**Comment by yuusuf-sallahuddin** [comment]
In my AI preferences I have all three units set to millimetres. So for whatever reason, it is not creating the font in millimetres height, but some other unit type (possibly points or pixels). Not a huge issue since I can always increase the size, just unexpected behaviour.

Also, a side thought, being able to select the font would be awesome too. I wonder, does it use a specific font currently or is it based off what font you currently have selected as your font for typing?

Side note 2, I am wondering is there a way for the Specify script to retain previously entered values (e.g. for font-size & colour) so it doesn't need to be re-entered every time? It would be nice if it could default to the previously used value.

**Comment by adamdehaven** [comment]
With the current version, the settings persist (once changed) until you close Illustrator. Do you not see this behavior.

**Example**:
1. Run the script the first time and change the font size to "20"
2. Run the script a second time for a different dimension and the dialog retains the font size "20" from the previous run.

**Comment by yuusuf-sallahuddin** [comment]
I didn't notice that when I tested it yesterday on the same file. I had to re-enter the values for every set of objects I spec'd. Will give it another test & report back.

**Comment by adamdehaven** [comment]
I believe font selection on the dimensions themselves might be a little overkill. As a workaround, you can select all of the elements in the SPEC layer and apply a Paragraph Style that changes the font family, font style, etc. all at once.

I'm still going to be looking into the default units suggestion.

**Comment by yuusuf-sallahuddin** [comment]
That's a good idea for the font selection. Just do it via the whole SPEC layer. Didn't think of that.

**Comment by adamdehaven** [comment]
> `textRange.characterAttributes.size`: **Font size in points.** 

Utilizing alternative units (i.e. mm) is not an option.

I've come up with a viable solution that converts the document's `RulerUnits` into points and added a units label on the **Font Size** input to allow users to specify the label font size in the same units as the document.

**Comment by adamdehaven** [comment]
@yuusuf-sallahuddin I've pushed the solution into the master branch. Please download the newest version (`1.2.1`) and let me know if it works as expected. Thanks for your input!

**Comment by yuusuf-sallahuddin** [comment]
@adamdehaven Works beautifully :) Also, I notice that the options are actually persisting for me with this new version. Thanks again.
